### ISSUE TITLE
Fetching devices

### ISSUE THREAD

**Issue by hchinyavada** [yodiyil/traccar-api-php#11] opened 2019-03-24 00:06 UTC
Hello i logged in using the function login and parsed in my credentials and returns an array with user information. then i fetched the token from the returned array and parsed it to positions to get all device positions but i am getting a 401 error. May anyone assist on this. If i am not mistaken the "$sessionId" is the "user token"???

**Comment by jaimzj** [comment] 2019-03-24 02:23
Hello,
Your title is asking about device and description you asking about positions.

It all depends on your code, as you are able to login successfully can you check what is the value in $sessionId ? I do not know what has been assigned to $sessionId in your code.

And for device positions what function are you calling? share some snippets from your code where exactly the problem is and I can try to help for sure.

**Comment by hchinyavada** [comment] 2019-03-24 09:47
Thank you for the response jaimzj.

Below I have attached my php code to populate the positions for my devices:


<?php
header('Content-Type: application/json');

include('traccarApi.php');

$gpsManager = new gps();

$email = "my_account_email";
$password = "my_account_password";

$login = $gpsManager->login($email, $password);

$login_response = $login->response;
$response_array = json_decode($login_response);

$sessionId = $response_array->token;

echo $sessionId."\n";

$positions = $gpsManager->positions($sessionId);

print_r($positions);

?>

**Comment by hchinyavada** [comment] 2019-03-24 09:49
Hello jaimzj below is my php code snippet:


<?php

header('Content-Type: application/json');

include('traccarApi.php');

$gpsManager = new gps();

$email = "my_account_email";
$password = "my_account_password";

$login = $gpsManager->login($email, $password);

$login_response = $login->response;
$response_array = json_decode($login_response);

$sessionId = $response_array->token;

echo $sessionId."\n";

$positions = $gpsManager->positions($sessionId);

print_r($positions);

?>

**Comment by jaimzj** [comment] 2019-03-24 13:47
the token value is used as alternative login credential.

Refer to the following link https://github.com/gpsguru/traccar-ui-php/blob/dfb101df6bf916629f21639d1b724c93e01e3554/loginDo.php#L9

For examples on login and the sessionId value.

**Comment by perfectwebtech** [comment] 2021-07-02 12:43
when full code uploaded by you for web ?

**Closed as completed** 2021-12-03 15:27 UTC
